apiVersion: chainsaw.kyverno.io/v1alpha2
kind: Configuration
metadata:
  creationTimestamp: null
  name: configuration
spec:
  timeouts:
    apply: 1m30s
    assert: 1m30s
    cleanup: 2m30s
    delete: 1m30s
    error: 1m30s
    exec: 1m30s
  execution:
    parallel: 1
    forceTerminationGracePeriod: 5s
  cleanup:
    delayBeforeCleanup: 3s
  discovery:
    fullName: true
    excludeTestRegex: 'dockerfile-*'
