apiVersion: v1
kind: Pod
metadata:
  name: badpod01-new
  annotations:
    nginx.ingress.kubernetes.io/server-snippet: |
      add_header X-Safe-Header "Safe Content";
      add_header X-Vuln-Header "Benign\r
      HTTP/1.1 200 OK
      Content-Type: text/html

      <script>alert('XSS');</script>
      --------";
      return 200 "Original Content";
spec:
  containers:
  - name: nginx-controller
    image: registry.k8s.io/ingress-nginx/controller:v1.11.3
---
apiVersion: v1
kind: Pod
metadata:
  name: badpod02-new
spec:
  containers:
  - name: nginx-controller
    image: registry.k8s.io/ingress-nginx/controller:v1.11.1
  - name: nginx-controller-1
    image: registry.k8s.io/ingress-nginx/controller:v1.10.9
---
apiVersion: v1
kind: Pod
metadata:
  name: badpod03-new
  annotations:
    nginx.ingress.kubernetes.io/auth-tls-verify-client: "skip"
spec:
  containers:
  - name: nginx-controller
    image: registry.k8s.io/ingress-nginx/controller:v1.11.3
