apiVersion: v1
kind: Pod
metadata:
  name: goodpod01-new
  annotations:
    nginx.ingress.kubernetes.io/auth-tls-verify-client: "on"
spec:
  containers:
  - name: nginx-controller
    image: registry.k8s.io/ingress-nginx/controller:v1.11.3
