apiVersion: apps/v1
kind: Deployment
metadata:
  name: gooddeployment01-new
  annotations:
    nginx.ingress.kubernetes.io/auth-tls-verify-client: "on"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: nginx-controller
        image: registry.k8s.io/ingress-nginx/controller:v1.11.3
      - name: nginx-controller-1
        image: registry.k8s.io/ingress-nginx/controller:v1.11.4
