apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: validate-nginx-ingress-controller
  annotations:
    policies.kyverno.io/title: CVE-2024-7646 Nginx Ingress Controller
    policies.kyverno.io/category: Mitigate CVEs
    policies.kyverno.io/severity: critical
    policies.kyverno.io/description: >-
      A security issue was discovered in ingress-nginx where an actor with permission to create Ingress objects (in the `networking.k8s.io` or `extensions` API group) can bypass annotation validation to inject arbitrary commands and obtain the credentials of the ingress-nginx controller. In the default configuration, that credential has access to all secrets in the cluster. (Reference: https://nvd.nist.gov/vuln/detail/CVE-2024-7646)
spec:
  validationFailureAction: Enforce
  background: true
  rules:
  - name: validate-ingress-annotations
    match:
      resources:
        kinds:
        - Ingress
    validate:
      message: "The annotation nginx.ingress.kubernetes.io/server-snippet is not allowed."
      pattern:
        metadata:
          annotations:
            X(*-snippet): "?*"
  - name: validate-auth-tls-verify-client
    match:
      resources:
        kinds:
        - Ingress
    validate:
      message: "auth-tls-verify-client annotation must be one of 'on', 'off', 'optional', or 'optional_no_ca'."
      deny:
        conditions:
          any:
          - key: "{{request.object.metadata.annotations.\"nginx.ingress.kubernetes.io/auth-tls-verify-client\"}}"
            operator: AnyNotIn
            value:
            - "on"
            - "off"
            - "optional"
            - "optional_no_ca"

  - name: deny-lower-ingress-nginx-controller-versions
    match:
      resources:
        kinds:
          - Pod
    validate:
      message: "The ingress-nginx controller image version must be v1.11.2 or greater."
      deny:
        conditions:
          - key: "{{ request.object.spec.containers[?(@.name=='controller')].image }}"
            operator: AnyIn
            value:
              - "registry.k8s.io/ingress-nginx/controller:v1.11.0"
              - "registry.k8s.io/ingress-nginx/controller:v1.11.1"
              - "registry.k8s.io/ingress-nginx/controller:v1.10.*"
              - "registry.k8s.io/ingress-nginx/controller:v1.9.*"
              - "registry.k8s.io/ingress-nginx/controller:v1.8.*"
              - "registry.k8s.io/ingress-nginx/controller:v1.7.*"
              - "registry.k8s.io/ingress-nginx/controller:v1.6.*"
              - "registry.k8s.io/ingress-nginx/controller:v1.5.*"
              - "registry.k8s.io/ingress-nginx/controller:v1.4.*"
              - "registry.k8s.io/ingress-nginx/controller:v1.3.*"
              - "registry.k8s.io/ingress-nginx/controller:v1.2.*"
              - "registry.k8s.io/ingress-nginx/controller:v1.1.*"
              - "registry.k8s.io/ingress-nginx/controller:v1.0.*"