apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: deny-loadbalancer-creation
  annotations:
    policices.kyverno.io/subject: "Service"
    policices.kyverno.io/severity: "medium"
    policies.kyverno.io/category: PCI DSS Compliance
    policices.kyverno.io/title: "deny LoadBalancer Creation"
    policices.kyverno.io/description: >-
      LoadBalancer type svc provides a Public IP address or dNS name to which the external users can connect.
      This policy blocks the creation of Kubernetes LoadBalancer type services.
spec:
  validationFailureAction: Audit
  background: true
  rules:
  - name: deny-loadbalancer-creation
    match:
      any:
      - resources:
          kinds:
          - Service
    validate:
      message: "LoadBalancer type service creation is not allowed."
      deny:
        conditions:
          all:
            - key: "{{request.object.spec.type}}"
              operator: Equal
              value: LoadBalancer
